- name: Setup automated daily system report
  hosts: local
  become: yes
  vars_files:
    - group_vars/local.yml

  pre_tasks:
    - name: Set user_id and home variables from environment
      set_fact:
        ansible_user_id: "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
        user_home: "{{ ansible_env.HOME | default('/root') }}"

  tasks:
    - name: Ensure msmtp is installed
      apt:
        name:
          - msmtp
          - msmtp-mta
        state: present
        update_cache: yes

    - name: Create .msmtprc file for root (cron use)
      template:
        src: msmtprc.j2
        dest: "/root/.msmtprc"
        owner: root
        group: root
        mode: '0600'

    - name: Create .msmtprc file for current user (test use)
      template:
        src: msmtprc.j2
        dest: "{{ lookup('env', 'HOME') + '/.msmtprc' }}"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0600'

    - name: Upload daily-upgrade.sh
      template:
        src: daily-upgrade.sh.j2
        dest: /usr/local/bin/daily-upgrade.sh
        mode: '0755'
        owner: root
        group: root

    - name: Ensure cron job is present
      cron:
        name: "Daily system report"
        minute: "0"
        hour: "4"
        job: "/usr/local/bin/daily-upgrade.sh"
        cron_file: "system-report"
        user: root
